server:
  port: 8080
spring:
  application:
    name: miniatutorizador
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/miniautorizador
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

